import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { connectToDatabase } from "@/lib/mongoose";
import Flashcard from "@/models/Flashcard";
import Note from "@/models/Note";
import { jsPDF } from "jspdf";

export async function GET(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await getServerSession();

    if (!session || !session.user?.email) {
      return NextResponse.json(
        { error: "You must be logged in" },
        { status: 401 }
      );
    }

    const { id } = await params;

    await connectToDatabase();

    const note = await Note.findById(id);
    const flashcards = await Flashcard.find({
      noteId: id,
      userId: session.user.email,
    });

    if (flashcards.length === 0) {
      return NextResponse.json({ error: "No flashcards found" }, { status: 404 });
    }

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 15;
    const maxWidth = pageWidth - margin * 2;
    let y = 20;

    doc.setFontSize(18);
    doc.text(note?.title || "Flashcards", margin, y);
    y += 10;

    doc.setFontSize(10);
    doc.setTextColor(120);
    doc.text(`${flashcards.length} cards — generated by Notes to Flashcards`, margin, y);
    y += 10;
    doc.setTextColor(0);

    flashcards.forEach((card, index) => {
      if (y > 260) {
        doc.addPage();
        y = 20;
      }

      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      const questionLines = doc.splitTextToSize(`${index + 1}. ${card.question}`, maxWidth);
      doc.text(questionLines, margin, y);
      y += questionLines.length * 6 + 2;

      doc.setFont("helvetica", "normal");
      doc.setTextColor(74, 124, 110);
      const answerLines = doc.splitTextToSize(`Answer: ${card.answer}`, maxWidth);
      doc.text(answerLines, margin, y);
      y += answerLines.length * 6 + 8;
      doc.setTextColor(0);
    });

    const pdfBuffer = Buffer.from(doc.output("arraybuffer"));

    return new NextResponse(pdfBuffer, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": "attachment; filename=flashcards.pdf",
      },
    });
  } catch (error) {
    console.error("PDF export error:", error);
    return NextResponse.json(
      { error: "Something went wrong" },
      { status: 500 }
    );
  }
}